const SET_QUESTION = 'SET_QUESTION'
const SET_COMMENT_CONTENT = 'SET_COMMENT_CONTENT'
const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
const SET_SHOW_EDIT_FIELDS = 'SET_SHOW_EDIT_FIELDS'
const SET_EDITED_QUESTION_TITLE = 'SET_EDITED_QUESTION_TITLE'
const SET_EDITED_QUESTION_CONTENT = 'SET_EDITED_QUESTION_CONTENT'
const SET_EDITED_QUESTION_TAGS = 'SET_EDITED_QUESTION_TAGS'
const SET_EDITED_QUESTION_TITLE_HELPER_TEXT = 'SET_EDITED_QUESTION_TITLE_HELPER_TEXT'
const SET_EDITED_QUESTION_CONTENT_HELPER_TEXT = 'SET_EDITED_QUESTION_CONTENT_HELPER_TEXT'
const SET_EDITED_QUESTION_TAGS_HELPER_TEXT = 'SET_EDITED_QUESTION_TAGS_HELPER_TEXT'
const SET_IS_QUESTION_SOLVED = 'SET_IS_QUESTION_SOLVED'
const SET_CLIPBOARD_SNACKBAR_OPEN = 'SET_CLIPBOARD_SNACKBAR_OPEN'

export default {
  SET_QUESTION,
  SET_COMMENT_CONTENT,
  SET_ERROR_MESSAGE,
  SET_SHOW_EDIT_FIELDS,
  SET_EDITED_QUESTION_TITLE,
  SET_EDITED_QUESTION_CONTENT,
  SET_EDITED_QUESTION_TAGS,
  SET_EDITED_QUESTION_TITLE_HELPER_TEXT,
  SET_EDITED_QUESTION_CONTENT_HELPER_TEXT,
  SET_EDITED_QUESTION_TAGS_HELPER_TEXT,
  SET_IS_QUESTION_SOLVED,
  SET_CLIPBOARD_SNACKBAR_OPEN,
}
